// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LibertyCore`

/// Initialize the Liberty Reach core.
/// Must be called once before any other function.
Future<String> init(
        {required String peerName,
        required String localaiUrl,
        required String storagePath}) =>
    RustLib.instance.api.crateApiLibertyApiInit(
        peerName: peerName, localaiUrl: localaiUrl, storagePath: storagePath);

/// Get the local Peer ID
Future<String> getPeerId() =>
    RustLib.instance.api.crateApiLibertyApiGetPeerId();

/// Get a list of connected peers
Future<List<String>> getConnectedPeers() =>
    RustLib.instance.api.crateApiLibertyApiGetConnectedPeers();

/// Send a chat message to the P2P network
Future<String> sendMessage({required String content}) =>
    RustLib.instance.api.crateApiLibertyApiSendMessage(content: content);

/// Ask the AI with text (Gemma via LocalAI)
Future<String> askAi({required String prompt}) =>
    RustLib.instance.api.crateApiLibertyApiAskAi(prompt: prompt);

/// Ask the AI with text + images (LLaVA multimodal)
Future<String> askAiMultimodal(
        {required String prompt, required List<String> imagesBase64}) =>
    RustLib.instance.api.crateApiLibertyApiAskAiMultimodal(
        prompt: prompt, imagesBase64: imagesBase64);

/// Connect to a peer by multiaddr
Future<String> connectToPeer({required String address}) =>
    RustLib.instance.api.crateApiLibertyApiConnectToPeer(address: address);

/// Check if AI server is healthy
Future<bool> checkAiHealth() =>
    RustLib.instance.api.crateApiLibertyApiCheckAiHealth();

/// Get recent messages from local storage
Future<List<MessageEntry>> getMessageHistory({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLibertyApiGetMessageHistory(limit: limit);

/// Initialize the Minima blockchain connection for DADA Point rewards.
/// Call after `init()`. `minima_url` is the Minima node RPC endpoint
/// (e.g. "http://localhost:8080" from Docker, or "https://your-node:1822").
Future<String> initMinima({required String minimaUrl}) =>
    RustLib.instance.api.crateApiLibertyApiInitMinima(minimaUrl: minimaUrl);

/// Get the local Minima node address
Future<String> getMinimaAddress() =>
    RustLib.instance.api.crateApiLibertyApiGetMinimaAddress();

/// Get the current DADA Point balance for the local Minima node
Future<DADABalance> getDadaBalance() =>
    RustLib.instance.api.crateApiLibertyApiGetDadaBalance();

/// Reward a user for watching a Loop video.
/// `user_address` is the Minima address to send DADA Points to.
/// `video_cid` is the content identifier for the video.
/// `seconds` is the watch duration in seconds.
Future<RewardResult> rewardForWatch(
        {required String userAddress,
        required String videoCid,
        required int seconds}) =>
    RustLib.instance.api.crateApiLibertyApiRewardForWatch(
        userAddress: userAddress, videoCid: videoCid, seconds: seconds);

/// Reward a user for an AI chat interaction
Future<RewardResult> rewardForAiChat(
        {required String userAddress,
        required String chatId,
        required int seconds}) =>
    RustLib.instance.api.crateApiLibertyApiRewardForAiChat(
        userAddress: userAddress, chatId: chatId, seconds: seconds);

/// Reward a user for P2P message relay
Future<RewardResult> rewardForRelay(
        {required String userAddress,
        required String relayId,
        required int seconds}) =>
    RustLib.instance.api.crateApiLibertyApiRewardForRelay(
        userAddress: userAddress, relayId: relayId, seconds: seconds);

/// Check if Minima node is healthy
Future<bool> checkMinimaHealth() =>
    RustLib.instance.api.crateApiLibertyApiCheckMinimaHealth();

/// DADA Point balance info
class DADABalance {
  final BigInt balance;
  final String address;

  const DADABalance({
    required this.balance,
    required this.address,
  });

  @override
  int get hashCode => balance.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DADABalance &&
          runtimeType == other.runtimeType &&
          balance == other.balance &&
          address == other.address;
}

/// Flutter-accessible message entry
class MessageEntry {
  final PlatformInt64 id;
  final String sender;
  final String content;
  final bool isAi;
  final String timestamp;

  const MessageEntry({
    required this.id,
    required this.sender,
    required this.content,
    required this.isAi,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      content.hashCode ^
      isAi.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          content == other.content &&
          isAi == other.isAi &&
          timestamp == other.timestamp;
}

/// Result of a reward action
class RewardResult {
  final int pointsEarned;
  final String txId;
  final String action;
  final bool success;
  final String error;

  const RewardResult({
    required this.pointsEarned,
    required this.txId,
    required this.action,
    required this.success,
    required this.error,
  });

  @override
  int get hashCode =>
      pointsEarned.hashCode ^
      txId.hashCode ^
      action.hashCode ^
      success.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RewardResult &&
          runtimeType == other.runtimeType &&
          pointsEarned == other.pointsEarned &&
          txId == other.txId &&
          action == other.action &&
          success == other.success &&
          error == other.error;
}
