// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/liberty_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2048218190;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'liberty_reach_core',
    ioDirectory: '../rust_core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiLibertyApiAskAi({required String prompt});

  Future<String> crateApiLibertyApiAskAiMultimodal(
      {required String prompt, required List<String> imagesBase64});

  Future<bool> crateApiLibertyApiCheckAiHealth();

  Future<bool> crateApiLibertyApiCheckMinimaHealth();

  Future<String> crateApiLibertyApiConnectToPeer({required String address});

  Future<List<String>> crateApiLibertyApiGetConnectedPeers();

  Future<DADABalance> crateApiLibertyApiGetDadaBalance();

  Future<List<MessageEntry>> crateApiLibertyApiGetMessageHistory(
      {required PlatformInt64 limit});

  Future<String> crateApiLibertyApiGetMinimaAddress();

  Future<String> crateApiLibertyApiGetPeerId();

  Future<String> crateApiLibertyApiInit(
      {required String peerName,
      required String localaiUrl,
      required String storagePath});

  Future<String> crateApiLibertyApiInitMinima({required String minimaUrl});

  Future<RewardResult> crateApiLibertyApiRewardForAiChat(
      {required String userAddress,
      required String chatId,
      required int seconds});

  Future<RewardResult> crateApiLibertyApiRewardForRelay(
      {required String userAddress,
      required String relayId,
      required int seconds});

  Future<RewardResult> crateApiLibertyApiRewardForWatch(
      {required String userAddress,
      required String videoCid,
      required int seconds});

  Future<String> crateApiLibertyApiSendMessage({required String content});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiLibertyApiAskAi({required String prompt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(prompt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiAskAiConstMeta,
      argValues: [prompt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiAskAiConstMeta => const TaskConstMeta(
        debugName: "ask_ai",
        argNames: ["prompt"],
      );

  @override
  Future<String> crateApiLibertyApiAskAiMultimodal(
      {required String prompt, required List<String> imagesBase64}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(prompt, serializer);
        sse_encode_list_String(imagesBase64, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiAskAiMultimodalConstMeta,
      argValues: [prompt, imagesBase64],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiAskAiMultimodalConstMeta =>
      const TaskConstMeta(
        debugName: "ask_ai_multimodal",
        argNames: ["prompt", "imagesBase64"],
      );

  @override
  Future<bool> crateApiLibertyApiCheckAiHealth() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiCheckAiHealthConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiCheckAiHealthConstMeta =>
      const TaskConstMeta(
        debugName: "check_ai_health",
        argNames: [],
      );

  @override
  Future<bool> crateApiLibertyApiCheckMinimaHealth() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiCheckMinimaHealthConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiCheckMinimaHealthConstMeta =>
      const TaskConstMeta(
        debugName: "check_minima_health",
        argNames: [],
      );

  @override
  Future<String> crateApiLibertyApiConnectToPeer({required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiConnectToPeerConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiConnectToPeerConstMeta =>
      const TaskConstMeta(
        debugName: "connect_to_peer",
        argNames: ["address"],
      );

  @override
  Future<List<String>> crateApiLibertyApiGetConnectedPeers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiGetConnectedPeersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiGetConnectedPeersConstMeta =>
      const TaskConstMeta(
        debugName: "get_connected_peers",
        argNames: [],
      );

  @override
  Future<DADABalance> crateApiLibertyApiGetDadaBalance() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dada_balance,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiGetDadaBalanceConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiGetDadaBalanceConstMeta =>
      const TaskConstMeta(
        debugName: "get_dada_balance",
        argNames: [],
      );

  @override
  Future<List<MessageEntry>> crateApiLibertyApiGetMessageHistory(
      {required PlatformInt64 limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_message_entry,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiGetMessageHistoryConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiGetMessageHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_message_history",
        argNames: ["limit"],
      );

  @override
  Future<String> crateApiLibertyApiGetMinimaAddress() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiGetMinimaAddressConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiGetMinimaAddressConstMeta =>
      const TaskConstMeta(
        debugName: "get_minima_address",
        argNames: [],
      );

  @override
  Future<String> crateApiLibertyApiGetPeerId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiGetPeerIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiGetPeerIdConstMeta =>
      const TaskConstMeta(
        debugName: "get_peer_id",
        argNames: [],
      );

  @override
  Future<String> crateApiLibertyApiInit(
      {required String peerName,
      required String localaiUrl,
      required String storagePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerName, serializer);
        sse_encode_String(localaiUrl, serializer);
        sse_encode_String(storagePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiInitConstMeta,
      argValues: [peerName, localaiUrl, storagePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiInitConstMeta => const TaskConstMeta(
        debugName: "init",
        argNames: ["peerName", "localaiUrl", "storagePath"],
      );

  @override
  Future<String> crateApiLibertyApiInitMinima({required String minimaUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(minimaUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiInitMinimaConstMeta,
      argValues: [minimaUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiInitMinimaConstMeta =>
      const TaskConstMeta(
        debugName: "init_minima",
        argNames: ["minimaUrl"],
      );

  @override
  Future<RewardResult> crateApiLibertyApiRewardForAiChat(
      {required String userAddress,
      required String chatId,
      required int seconds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userAddress, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_u_32(seconds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_reward_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiRewardForAiChatConstMeta,
      argValues: [userAddress, chatId, seconds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiRewardForAiChatConstMeta =>
      const TaskConstMeta(
        debugName: "reward_for_ai_chat",
        argNames: ["userAddress", "chatId", "seconds"],
      );

  @override
  Future<RewardResult> crateApiLibertyApiRewardForRelay(
      {required String userAddress,
      required String relayId,
      required int seconds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userAddress, serializer);
        sse_encode_String(relayId, serializer);
        sse_encode_u_32(seconds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_reward_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiRewardForRelayConstMeta,
      argValues: [userAddress, relayId, seconds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiRewardForRelayConstMeta =>
      const TaskConstMeta(
        debugName: "reward_for_relay",
        argNames: ["userAddress", "relayId", "seconds"],
      );

  @override
  Future<RewardResult> crateApiLibertyApiRewardForWatch(
      {required String userAddress,
      required String videoCid,
      required int seconds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userAddress, serializer);
        sse_encode_String(videoCid, serializer);
        sse_encode_u_32(seconds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_reward_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiRewardForWatchConstMeta,
      argValues: [userAddress, videoCid, seconds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiRewardForWatchConstMeta =>
      const TaskConstMeta(
        debugName: "reward_for_watch",
        argNames: ["userAddress", "videoCid", "seconds"],
      );

  @override
  Future<String> crateApiLibertyApiSendMessage({required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibertyApiSendMessageConstMeta,
      argValues: [content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibertyApiSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_message",
        argNames: ["content"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DADABalance dco_decode_dada_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DADABalance(
      balance: dco_decode_u_64(arr[0]),
      address: dco_decode_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MessageEntry> dco_decode_list_message_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageEntry dco_decode_message_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MessageEntry(
      id: dco_decode_i_64(arr[0]),
      sender: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      isAi: dco_decode_bool(arr[3]),
      timestamp: dco_decode_String(arr[4]),
    );
  }

  @protected
  RewardResult dco_decode_reward_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RewardResult(
      pointsEarned: dco_decode_u_32(arr[0]),
      txId: dco_decode_String(arr[1]),
      action: dco_decode_String(arr[2]),
      success: dco_decode_bool(arr[3]),
      error: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DADABalance sse_decode_dada_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balance = sse_decode_u_64(deserializer);
    var var_address = sse_decode_String(deserializer);
    return DADABalance(balance: var_balance, address: var_address);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageEntry> sse_decode_list_message_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageEntry sse_decode_message_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_isAi = sse_decode_bool(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    return MessageEntry(
        id: var_id,
        sender: var_sender,
        content: var_content,
        isAi: var_isAi,
        timestamp: var_timestamp);
  }

  @protected
  RewardResult sse_decode_reward_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pointsEarned = sse_decode_u_32(deserializer);
    var var_txId = sse_decode_String(deserializer);
    var var_action = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    return RewardResult(
        pointsEarned: var_pointsEarned,
        txId: var_txId,
        action: var_action,
        success: var_success,
        error: var_error);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_dada_balance(DADABalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.balance, serializer);
    sse_encode_String(self.address, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_entry(
      List<MessageEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_entry(MessageEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.isAi, serializer);
    sse_encode_String(self.timestamp, serializer);
  }

  @protected
  void sse_encode_reward_result(RewardResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pointsEarned, serializer);
    sse_encode_String(self.txId, serializer);
    sse_encode_String(self.action, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
